name: "Upload to Primer Spec Preview"
description: "GitHub Action to upload a Jekyll site preview to Primer Spec Preview"
author: "Sesh Sadasivam"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "set secrets.GITHUB_TOKEN here"
  PRIMER_SPEC_PREVIEW_SECRET:
    required: true
    description: "include the secret expected by Primer Spec Preview"
  site_directory_path:
    required: false
    default: "_site"
    description: "path to directory containing site to be previewed"
runs:
  using: "node12"
  main: "dist/index.js"
